Entrega Proyecto 1
leandrodavid/proyecto-1 pull request #1
Opened 2020-05-15 03:57 UTC by leandrodavid

### Entrega Proyecto 1

- Tema Elegido:  2
- Link a GitHub Pages: [link](https://leandrodavid.github.io/proyecto-1/) 

La entrega esta realizada tarde y por lo que veo no funciona en GitHub Pages.
Ante todo quería entregarlo igual, para tener posibilidad de re entrega.

2020-05-16 02:24 UTC, leandrodavid commented
Hola Fernando, te dejo el enlace al video.
https://drive.google.com/open?id=1VrxT_FoUVqV2DsywnPN2ZXmG16ohu1oC

Saludos

2020-05-19 18:14 UTC, hfmartinez85 requested changes
# Proyecto 1 - Mara

7. PR a tiempo: No

**Comentarios**: El alumno informa en el PR que la entrega fue realizada tarde y no funciona en GitHub Pages, pero que quería presentarlo igual para tener posibilidad de re entrega. Se evaluará en la reentrega.

**Resultado**: Re-entrega

Hola Fernando, te queria consultar si no hay problema en usar la librería  phaser para realizar el juego? . Al final andaba en GitHub Pages, se ve que cuando me fije algo paso. Igual esta muy feo , así que a mejorarlo.
Saludos,
Leandro.

2020-05-26 14:13 UTC, hfmartinez85 commented
Hola, podés usar librerías de terceros para mejorar el proyecto siempre que des el crédito correspondiente y dejes el link a la fuente.
Saludos!

2020-05-27 00:06 UTC, leandrodavid commented
RE entrega Proyecto 1
Tema Elegido: 2
Link a GitHub Pages: https://leandrodavid.github.io/proyecto-1/
Link al video : https://drive.google.com/open?id=1UjidquVzSjeOl6Tq5BzktL79fbIXld63

2020-05-27 00:15 UTC, merged

2020-05-27 01:19 UTC, leandrodavid commented
Creo que me la mande en el PR.